name: "POCSAG Gateway"
version: "0.2.1"
slug: "pocsag_gateway"
description: "Modtager POCSAG 2400 på 171,300 MHz med RTL-SDR Blog V4 og sender til MQTT"
stage: experimental
arch:
  - aarch64
startup: application
boot: auto
init: false
usb: true
udev: true
services:
  - mqtt:need
options:
  frequency: "171.300M"
  sample_rate: 22050
  gain: "auto"
  ppm: 0
  squelch: 0
  mqtt_base_topic: "pager"
  mqtt_discovery_prefix: "homeassistant"
  retain_last_message: true
schema:
  frequency: str
  sample_rate: int(8000,48000)
  gain: str
  ppm: int
  squelch: int(0,1000)
  mqtt_base_topic: str
  mqtt_discovery_prefix: str
  retain_last_message: bool
